import Foundation
import Combine

enum Lang: String {
    case pt, en
}

final class Localization: ObservableObject {
    static let shared = Localization()

    @Published var lang: Lang {
        didSet { UserDefaults.standard.set(lang.rawValue, forKey: "imahjong-lang") }
    }

    private init() {
        if let stored = UserDefaults.standard.string(forKey: "imahjong-lang"), let l = Lang(rawValue: stored) {
            lang = l
        } else {
            lang = .pt
        }
    }

    func toggle() {
        lang = lang == .pt ? .en : .pt
    }

    func t(_ key: String) -> String {
        strings[lang]?[key] ?? key
    }

    private let strings: [Lang: [String: String]] = [
        .pt: [
            "tapToContinue": "Toque para continuar",
            "developedBy": "Desenvolvido por",

            "menuTag": "MAHJONG SOLITÁRIO",
            "menuSubtitle": "Combine pares. Limpe o tabuleiro. Relaxe.",
            "play": "Jogar",
            "howToPlay": "Como Jogar",
            "continueGame": "Continuar Jogo",
            "traditionalMode": "4 Jogadores (Riichi)",

            "difficultyLabel": "Dificuldade",
            "difficultyEasy": "Fácil",
            "difficultyMedium": "Médio",
            "difficultyHard": "Difícil",

            "tradSetupTitle": "4 Jogadores — Riichi",
            "tradSetupSubtitle": "Escolhe quantos lugares são humanos — o resto é preenchido por bots.",
            "humanPlayers": "Jogadores humanos",
            "startMatch": "Começar Partida",
            "windE": "Este", "windS": "Sul", "windW": "Oeste", "windN": "Norte",
            "you": "Tu",
            "bot": "Bot",
            "wallLeft": "Muralha",
            "roundLabel": "Ronda",
            "handLabel": "Mão",
            "doraLabel": "Dora",
            "pointsLabel": "Pontos",
            "riichiBtn": "Riichi",
            "tsumoBtn": "Tsumo",
            "ronBtn": "Ron",
            "ponBtn": "Pon",
            "chiBtn": "Chi",
            "kanBtn": "Kan",
            "passBtn": "Passar",
            "waitingOthers": "A aguardar pelos outros jogadores…",
            "yourTurnDiscard": "A tua vez — toca numa ficha para descartar.",
            "tsumoWinTitle": "Tsumo!",
            "ronWinTitle": "Ron!",
            "exhaustiveDrawTitle": "Muralha esgotada",
            "tenpaiLabel": "Em espera (tenpai)",
            "notenLabel": "Sem espera (noten)",
            "yakuLabel": "Yaku",
            "hanLabel": "Han",
            "fuLabel": "Fu",
            "totalPoints": "Pontuação",
            "nextHand": "Próxima Mão",
            "matchEndTitle": "Fim da Partida",
            "finalStandings": "Classificação Final",
            "riichiSticksLabel": "Paus de Riichi na mesa",
            "noYakuWarning": "Esta mão ainda não tem yaku — não é possível declarar vitória.",
            "playLocal": "Jogar Localmente",

            "back": "Voltar",
            "menu": "Menu",
            "time": "Tempo",
            "moves": "Jogadas",
            "score": "Pontos",
            "left": "Restantes",
            "hint": "Dica",
            "shuffle": "Baralhar",
            "undo": "Desfazer",
            "restart": "Reiniciar",
            "restartConfirm": "Recomeçar este jogo? O progresso atual perde-se.",
            "confirmYes": "Sim",
            "confirmNo": "Cancelar",

            "winTitle": "Vitória!",
            "winSubtitle": "Limpaste o tabuleiro por completo.",
            "stuckTitle": "Sem jogadas disponíveis",
            "stuckSubtitle": "Já não há pares livres para combinar. Podes baralhar as fichas restantes ou desfazer a última jogada.",
            "playAgain": "Jogar Novamente",
            "backToMenu": "Voltar ao Menu",
            "finalTime": "Tempo final",
            "finalMoves": "Jogadas",
            "finalScore": "Pontuação",
            "noHintsLeft": "Sem mais dicas disponíveis neste jogo.",
            "noMoreUndo": "Não há jogadas para desfazer.",
            "shuffleImpossible": "Não foi possível encontrar um baralhar resolúvel. Tenta desfazer.",

            "htpTitle": "Como Jogar",
            "htpIntro": "O Mahjong Solitário joga-se com 144 fichas empilhadas em pirâmide. O objetivo é remover todas as fichas do tabuleiro, combinando-as duas a duas.",
            "htpFreeTitle": "1. A regra da ficha \"livre\"",
            "htpFreeBody": "Só podes selecionar uma ficha se ela estiver livre: nada por cima dela, e pelo menos um dos lados (esquerdo ou direito) completamente desimpedido.",
            "htpCoveredLabel": "Coberta",
            "htpCoveredDesc": "Tem uma ficha por cima — não pode ser jogada.",
            "htpBlockedLabel": "Bloqueada",
            "htpBlockedDesc": "Livre de fichas por cima, mas presa dos dois lados — não pode ser jogada.",
            "htpFreeLabel": "Livre",
            "htpFreeDesc": "Sem nada por cima e com um dos lados aberto — pode ser jogada.",
            "htpMatchTitle": "2. Como combinar fichas",
            "htpMatchBody": "Toca em duas fichas livres do mesmo tipo para as remover. As Flores e as Estações são especiais: qualquer Flor combina com qualquer outra Flor, e qualquer Estação com qualquer outra Estação — não precisam de ser iguais.",
            "htpToolsTitle": "3. Ferramentas de apoio",
            "htpHintBody": "realça um par jogável no tabuleiro. Tens um número limitado por jogo.",
            "htpShuffleBody": "reorganiza as fichas restantes, mantendo sempre uma solução possível, caso fiques sem jogadas.",
            "htpUndoBody": "repõe o último par removido.",
            "htpRiichiTitle": "4. Modo 4 Jogadores (Riichi)",
            "htpRiichiIntro": "Um jogo à parte, com regras tradicionais de Riichi Mahjong. Tu e três bots sentam-se à volta da mesa; o objetivo é fechar uma mão completa — quatro grupos de três fichas mais um par.",
            "htpRiichiTurnBody": "Em cada turno compras uma ficha e descartas outra. As fichas descartadas ficam visíveis para todos.",
            "htpRiichiCallsBody": "Podes reclamar o descarte de outro jogador: Pon forma um trio, Chi forma uma sequência (só do jogador à tua esquerda), Kan forma um quarteto. Chamar uma ficha abre a tua mão.",
            "htpRiichiRiichiTitle": "Riichi",
            "htpRiichiRiichiBody": "declara quando a tua mão fechada está a uma ficha da vitória (tenpai). Custa 1000 pontos e avisa os outros jogadores, mas aumenta a tua pontuação se ganhares.",
            "htpRiichiWinTitle": "Vitória",
            "htpRiichiWinBody": "Tsumo — ganhas com a ficha que compraste. Ron — ganhas reclamando o descarte de outro jogador.",
            "htpCloseButton": "Entendido",
        ],
        .en: [
            "tapToContinue": "Tap to continue",
            "developedBy": "Developed by",

            "menuTag": "MAHJONG SOLITAIRE",
            "menuSubtitle": "Match pairs. Clear the board. Unwind.",
            "play": "Play",
            "howToPlay": "How to Play",
            "continueGame": "Continue Game",
            "traditionalMode": "4-Player (Riichi)",

            "difficultyLabel": "Difficulty",
            "difficultyEasy": "Easy",
            "difficultyMedium": "Medium",
            "difficultyHard": "Hard",

            "tradSetupTitle": "4-Player — Riichi",
            "tradSetupSubtitle": "Choose how many seats are human — the rest are filled by bots.",
            "humanPlayers": "Human players",
            "startMatch": "Start Match",
            "windE": "East", "windS": "South", "windW": "West", "windN": "North",
            "you": "You",
            "bot": "Bot",
            "wallLeft": "Wall",
            "roundLabel": "Round",
            "handLabel": "Hand",
            "doraLabel": "Dora",
            "pointsLabel": "Points",
            "riichiBtn": "Riichi",
            "tsumoBtn": "Tsumo",
            "ronBtn": "Ron",
            "ponBtn": "Pon",
            "chiBtn": "Chi",
            "kanBtn": "Kan",
            "passBtn": "Pass",
            "waitingOthers": "Waiting for other players…",
            "yourTurnDiscard": "Your turn — tap a tile to discard.",
            "tsumoWinTitle": "Tsumo!",
            "ronWinTitle": "Ron!",
            "exhaustiveDrawTitle": "Wall Exhausted",
            "tenpaiLabel": "Ready (tenpai)",
            "notenLabel": "Not ready (noten)",
            "yakuLabel": "Yaku",
            "hanLabel": "Han",
            "fuLabel": "Fu",
            "totalPoints": "Score",
            "nextHand": "Next Hand",
            "matchEndTitle": "Match Over",
            "finalStandings": "Final Standings",
            "riichiSticksLabel": "Riichi sticks on the table",
            "noYakuWarning": "This hand has no yaku yet — you cannot declare a win.",
            "playLocal": "Play Locally",

            "back": "Back",
            "menu": "Menu",
            "time": "Time",
            "moves": "Moves",
            "score": "Score",
            "left": "Left",
            "hint": "Hint",
            "shuffle": "Shuffle",
            "undo": "Undo",
            "restart": "Restart",
            "restartConfirm": "Restart this game? Current progress will be lost.",
            "confirmYes": "Yes",
            "confirmNo": "Cancel",

            "winTitle": "You Win!",
            "winSubtitle": "You cleared the entire board.",
            "stuckTitle": "No Moves Available",
            "stuckSubtitle": "There are no free matching pairs left. You can shuffle the remaining tiles or undo the last move.",
            "playAgain": "Play Again",
            "backToMenu": "Back to Menu",
            "finalTime": "Final time",
            "finalMoves": "Moves",
            "finalScore": "Score",
            "noHintsLeft": "No more hints available this game.",
            "noMoreUndo": "Nothing to undo.",
            "shuffleImpossible": "Couldn't find a solvable shuffle. Try undo instead.",

            "htpTitle": "How to Play",
            "htpIntro": "Mahjong Solitaire is played with 144 tiles stacked into a pyramid. The goal is to clear the whole board by matching tiles two at a time.",
            "htpFreeTitle": "1. The \"free tile\" rule",
            "htpFreeBody": "You can only select a tile if it is free: nothing on top of it, and at least one side (left or right) completely open.",
            "htpCoveredLabel": "Covered",
            "htpCoveredDesc": "Has a tile stacked on top — cannot be played.",
            "htpBlockedLabel": "Blocked",
            "htpBlockedDesc": "Nothing on top, but boxed in on both sides — cannot be played.",
            "htpFreeLabel": "Free",
            "htpFreeDesc": "Nothing on top and one side open — can be played.",
            "htpMatchTitle": "2. Matching tiles",
            "htpMatchBody": "Tap two free tiles of the same type to remove them. Flowers and Seasons are special: any Flower matches any other Flower, and any Season matches any other Season — they don't need to be identical.",
            "htpToolsTitle": "3. Helper tools",
            "htpHintBody": "highlights one playable pair on the board. You get a limited number per game.",
            "htpShuffleBody": "rearranges the remaining tiles while always keeping a possible solution, in case you run out of moves.",
            "htpUndoBody": "brings back the last pair you removed.",
            "htpRiichiTitle": "4. 4-Player Mode (Riichi)",
            "htpRiichiIntro": "A separate game with traditional Riichi Mahjong rules. You and three bots sit around the table; the goal is to complete a hand — four groups of three tiles plus a pair.",
            "htpRiichiTurnBody": "Each turn you draw a tile and discard one. Discarded tiles stay visible to everyone.",
            "htpRiichiCallsBody": "You can claim another player's discard: Pon forms a triplet, Chi forms a sequence (only from the player to your left), Kan forms a quad. Calling a tile opens your hand.",
            "htpRiichiRiichiTitle": "Riichi",
            "htpRiichiRiichiBody": "declare when your closed hand is one tile away from winning (tenpai). Costs 1000 points and tips off the other players, but raises your score if you win.",
            "htpRiichiWinTitle": "Winning",
            "htpRiichiWinBody": "Tsumo — you win off the tile you just drew. Ron — you win by claiming another player's discard.",
            "htpCloseButton": "Got it",
        ],
    ]
}
